# Generated by Django 5.1.15 on 2026-08-17 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('league', models.CharField(max_length=100)),
                ('patch', models.CharField(max_length=50)),
                ('source', models.CharField(max_length=500)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'unique_together': {('league', 'patch')},
            },
        ),
    ]
