# Generated by Django 5.1.15 on 2026-08-17 22:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crafting", "0003_modgroup_mod"),
    ]

    operations = [
        migrations.CreateModel(
            name="SpawnWeight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("weight", models.PositiveIntegerField()),
                ("order", models.PositiveSmallIntegerField()),
                (
                    "mod",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="spawn_weights",
                        to="crafting.mod",
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="spawn_weights",
                        to="crafting.tag",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
                "indexes": [models.Index(fields=["tag"], name="crafting_sp_tag_id_33874b_idx")],
                "unique_together": {("mod", "order")},
            },
        ),
    ]
