# Generated by Django 5.1.15 on 2026-08-17 22:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crafting", "0004_spawnweight"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="baseitemtype",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="mod",
            name="group",
        ),
        migrations.AddField(
            model_name="baseitemtype",
            name="metadata_id",
            field=models.CharField(default="", max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="mod",
            name="groups",
            field=models.ManyToManyField(related_name="mods", to="crafting.modgroup"),
        ),
        migrations.AddField(
            model_name="mod",
            name="tags",
            field=models.ManyToManyField(blank=True, related_name="tagged_mods", to="crafting.tag"),
        ),
        migrations.AlterField(
            model_name="baseitemtype",
            name="name",
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="mod",
            name="generation_type",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name="baseitemtype",
            unique_together={("data_version", "metadata_id")},
        ),
        migrations.CreateModel(
            name="GenerationWeight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("value", models.PositiveIntegerField()),
                ("order", models.PositiveSmallIntegerField()),
                (
                    "mod",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="generation_weights",
                        to="crafting.mod",
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="generation_weights",
                        to="crafting.tag",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
                "unique_together": {("mod", "order")},
            },
        ),
    ]
